---
- name: role rust | manage pacman packages
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ rust_pacman_packages }}"

- name: ensure cargo bin is in the PATH
  include_role: name=zsh
  vars:
    zsh_config:
      - name: rust
        config: PATH=${PATH}:{{ cargo_bin_dir }}
        state: present

- name: Ensure {{ cargo_packages | map(attribute='name') }} cargo packages are managed
  shell: cargo install  {{ item.name }}
  with_items: "{{ cargo_packages }}"
  changed_when: "'is already installed' not in cargo_install_log.stdout"
  register: cargo_install_log
  when: item.state == "present"

- name: Ensure {{ cargo_packages | map(attribute='name') }} cargo packages are managed
  shell: cargo uninstall {{ item.name }}
  with_items: "{{ cargo_packages }}"
  register: cargo_uninstall_log
  when: item.state == "absent"
