---
- name: ensure rust package is managed
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: rust

- name: build cargo packages
  include_tasks: install_package.yml
  with_items: "{{ cargo_packages }}"
  when: cargo_packages | length

- name: add cargo bin path to zshrc
  include_role:
    name: zsh
    tasks_from: append_to_config.yml
  vars:
    item_block: PATH=${PATH}:{{ cargo_bin_dir }}
    item_name: rust

