---
- name: install shared dependencies
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: "{{ aur_shared_packages }}"

- name: install paru
  include_role:
    name: rust
  tasks_from: install_package.yml
  with_items:
    - paru
