---
docker_pacman_packages:
  - name: docker
    state: latest
  - name: docker-compose
    state: latest

docker_systemd_services:
  - name: docker.service
    state: started
    enabled: true
    masked: False
    fail_on_error: True
