---
- name: ensure ansible managed config created
  shell: 
    cmd: touch {{ zsh.ansible_managed_config }}
    creates: "{{ zsh.ansible_managed_config }}"

- name: append to ansible managed zsh config {{ item.name }}
  blockinfile:
    path: "{{ zsh.ansible_managed_config }}"
    block: "{{ item.block }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  when:
    - item.block | length
    - item.name | length
