---
- name: ensure ansible managed config created
  shell: 
    cmd: touch {{ zsh.ansible_managed_config }}
    creates: "{{ zsh.ansible_managed_config }}"
- name: append to ansible managed zsh config {{ item_name }}
  blockinfile:
    path: "{{ zsh.ansible_managed_config }}"
    block: "{{ item_block }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item_name }}"
  when: item_block | length
