---
- name: clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ zsh.ohmyzsh_dir }}

- name: ensure ~/.config/zsh is linked to zsh/files
  file:
    src: "{{ role_path }}/files/zsh"
    dest: "{{ zsh.config_dir }}"
    state: link
    force: true

- name: ensure ansible managed config created
  shell: 
    cmd: touch {{ zsh.ansible_managed_config }}
    creates: "{{ zsh.ansible_managed_config }}"

- name: ensure plugin repos are installed
  git: repo={{ item.repo }} dest={{ zsh.ohmyzsh_dir }}/custom/plugins/{{ item.name }}
  with_items: "{{ zsh.ohmyzsh_plugins }}"
  when: item.repo is defined

- name: ensure ~/.exports is created
  shell: 
    cmd: touch ~/.exports
    creates: ~/.exports

- name: symlink zshrc
  file:
    src: "{{ zsh.config_dir }}/.zshrc"
    path: ~/.zshrc 
    state: link
    force: true

- name: render plugins to ansible managed config
  include_tasks: append_to_config.yml
  vars:
    item_block: "{{ lookup('template', './settings.zsh') }}"
    item_name: role/zsh
