---
- name: ensure zsh is managed
  include_tasks: setup.yml
  when: zsh_is_managed is not defined

- name: ensure zsh config is up-to-date
  blockinfile:
    path: "{{ zsh_config_src }}"
    block: "{{ item.config }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    insertafter: "# ZSH ANSIBLE GENERATED CONFIG"
    state: "{{ item.state }}"
  with_items: "{{ zsh_config }}"
  when: item.config is defined






