---
- name: register zsh path
  shell: which zsh
  register: which_zsh
  changed_when: false

- name: ensure zsh is a current user shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ which_zsh.stdout }}"

