---
- name: ensure ripgrep is managed
  include_role:
    name: meta_pacman
  vars:
    packages: ripgrep

- name: set ripgrep as a vimgrep
  include_role:
    name: nvim
    tasks_from: append_to_config.yml
  vars:
    settings: |
      if executable('rg')
        set grepprg=rg\ --color=never\ --vimgrep
      endif
