---
- name: role ripgrep | manage pacman packages
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: "{{ ripgrep_pacman_packages }}"

- name: set ripgrep as a vimgrep
  include_role:
    name: nvim
  vars:
    nvim_config:
      - name: ripgrep
        block: |
          if executable('rg')
            set grepprg=rg\ --color=never\ --vimgrep
          endif
