---
zsh_config_dir: "{{ ansible_env.XDG_CONFIG_HOME }}/zsh"
ohmyzsh_dir: "{{ ansible_env.HOME }}/.oh-my-zsh"
ohmyzsh_plugins_dir: "{{ ohmyzsh_dir }}/custom/plugins"

# TODO:
zsh:
  ansible_managed_config: "{{ zsh_config_dir }}/config.ansible_provisioned.zsh"
