---
- name: role git | manage pacman packages
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: "{{ git_pacman_packages }}"

- name: role git | manage aur packages
  include_role:
    name: aur
  vars:
    aur_packages: "{{ git_aur_packages }}"

- name: ensure {{ item.name }} is configured
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: "{{ item.scope | default('global') }}"
  with_items: "{{ git_config }}"

