---
- name: role font-iosevka | ensure pacman packages are managed
  include_role: name=aur
  vars:
    aur_packages: "{{ font_iosevka_aur_packages }}"

- name: ensure alacritty config is up to date
  include_role: name=alacritty
  vars:
    alacritty_config:
      - name: font-iosevka
        block: |
          font:
            normal:
              family: iosevka
            size: 12.0
  tags: [alacritty]
