---
- name: role yarn | manage pacman packages
  include_role:
    name: meta_pacman
  vars:
    pacman_packages: "{{ yarn_pacman_packages }}"

- name: ensure yarn bin directory is added to the PATH
  include_role:
    name: zsh
  vars:
    zsh_config:
      - name: nodejs
        config: PATH=${PATH}:$(yarn global bin)
        state: present
  tags: [zsh]

- name: manage {{ item.name }} yarn package
  include_tasks: manage_package.yml
  with_items: "{{ yarn_packages }}"
