---
- name: ensure yarn and node are managed
  include_tasks: setup.yml
  when: yarn_is_managed is not defined

- name: manage {{ item.name }} yarn package
  include_tasks: manage_package.yml
  with_items: "{{ yarn_packages }}"
