---
- name: role sway | ensure packman packages are managed
  include_role: name=meta_pacman
  vars:
    pacman_packages: "{{ sway_pacman_packages }}"

- name: ensure config directories are exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ sway_config_dest | dirname }}"
    - "{{ waybar_config_dest | dirname }}"

- name: ensure configs are linked
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - src: "{{ waybar_config_src }}"
      dest: "{{ waybar_config_dest }}"
    - src: "{{ sway_config_src }}"
      dest: "{{ sway_config_dest }}"
