---
- name: ensure config_dir exist
  file:
    path: "{{ nvim_config_dir }}"
    state: directory

- name: ensure ~/.config/nvim/init.vim is linked to nvim/files/init.vim
  file:
    src: "{{ role_path }}/files/init.vim"
    dest: "{{ nvim_config_dir }}/init.vim"
    state: link
    force: true

- name: add plugins to config
  include_tasks: add_plugin_to_config.yml
  with_items:
    - name: nvim-pligins
      block: "{{ lookup('template', './plugins.vim') }}"

- name: append plugin settings
  block:
    - name: append settings
      include_tasks: append_to_config.yml
      with_items: 
        - "{{ nvim_plugins | json_query('[].{ name: name, block: settings  }') }}"
      vars:
        suffix: '-settings'

    - name: append plugin keybindings
      include_tasks: append_to_config.yml
      with_items: 
        - "{{ nvim_plugins | json_query('[].{ name: name, block: keybindings }') }}"
      vars:
        suffix: '-keybindings'

- name: install plugins
  shell: nvim +'PlugInstall --sync' +qall
  register: nvim_log
  changed_when: false

- name: set nvim as a git core.editor
  git_config:
    name: core.editor
    value: nvim
    scope: global

- name: export editor and visual
  include_role:
    name: zsh
  vars:
    zsh_settings:
      - name: nvim-configure
        block: |
          export EDITOR=nvim
          export VISUAL=nvim
  tags: [zsh]


