---
- name: ensure nvim is managed
  include_tasks: setup.yml
  when: nvim_is_managed is not defined

- name: ensure config is up-to-date
  blockinfile:
    path: "{{ nvim_config_src }}"
    block: "{{ item.config }}"
    state: "{{ item.state | default('present') }}"
    marker: "\" {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items: 
    - "{{ nvim_config }}"
  when: item.config is defined
